import {store} from './store.js';
import {esc,toast,download,modal} from './render.js';
export function loginDialog(onSuccess){
  const d=modal('Willkommen zurück.',`<p>Melde dich in deinem persönlichen Lernraum an.</p><form class="form-stack"><label>E-Mail<input name="email" type="email" autocomplete="username" required maxlength="254"></label><label>Passwort<input name="password" type="password" autocomplete="current-password" required></label><p id="login-error" class="error-message" role="alert"></p><button class="button">Anmelden ↗</button></form><p style="font-size:11px;margin-top:18px" class="muted">Dein Konto wird von einem Admin der Lerngruppe angelegt.</p>`);
  d.querySelector('form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),button=e.currentTarget.querySelector('button');button.disabled=true;try{await store.login(f.get('email'),f.get('password'));d.close();onSuccess();toast('Du bist angemeldet.');}catch(error){d.querySelector('#login-error').textContent=error.message;}finally{button.disabled=false;}};
}
export function accountDialog(onUpdate){
  if(!store.local&&!store.user)return loginDialog(onUpdate);
  const d=modal(store.local?'Dein persönlicher Lernraum':store.user.name,`<p>${store.local?'Deine Daten werden in diesem Browser gespeichert. Mit einem Backup kannst du sie sichern und später in dein Konto übernehmen.':`Angemeldet als ${esc(store.user.email)} · Rolle: ${esc({admin:'Admin',editor:'Editor',user:'Studierende'}[store.user.role])}`}</p><div class="form-stack"><button class="button" id="export-personal">Persönliches Backup exportieren ↗</button><button class="button secondary" id="restore-personal">Persönliche Daten importieren</button>${!store.local?'<button class="button secondary" id="change-password">Passwort ändern</button>':''}${store.user?.role==='admin'?'<button class="button secondary" id="manage-users">Lerngruppe verwalten</button>':''}<a class="text-button" href="#/editor" id="open-editor">Inhalte verwalten ↗</a>${!store.local?'<button class="text-button" id="logout">Abmelden</button>':''}</div><p class="muted" style="font-size:11px;margin-top:20px">Das persönliche Backup enthält auch deine privaten Notizen.</p>`);
  d.querySelector('#export-personal').onclick=()=>download('ebl-persoenliches-backup.json',store.exportAll());
  d.querySelector('#open-editor').onclick=()=>d.close();
  d.querySelector('#restore-personal').onclick=()=>{const r=modal('Persönliches Backup importieren',`<p>Ersetzt deinen bisherigen persönlichen Lernstand, Notizen, Kartenbewertungen und Lernplan. Der gemeinsame Kurskatalog wird dabei nicht geändert.</p><label>Backup-Datei<input id="backup-file" type="file" accept=".json,application/json"></label><p id="backup-error" role="alert" class="error-message"></p><button class="button" id="restore-confirm" style="margin-top:20px">Persönliche Daten übernehmen</button>`);r.querySelector('#restore-confirm').onclick=async()=>{try{const file=r.querySelector('#backup-file').files[0];if(!file)throw new Error('Bitte wähle eine Backup-Datei.');if(file.size>5*1024*1024)throw new Error('Maximal 5 MB pro Backup.');const parsed=JSON.parse(await file.text());if(!parsed.state)throw new Error('Diese Datei enthält keinen persönlichen Lernstand.');await store.restorePersonal(parsed.state);r.close();onUpdate();toast('Deine persönlichen Daten wurden importiert.');}catch(error){r.querySelector('#backup-error').textContent=error.message;}};};
  if(!store.local){d.querySelector('#logout').onclick=async()=>{try{await store.logout();d.close();onUpdate();toast('Du bist abgemeldet.');}catch(e){toast(e.message);}};
    d.querySelector('#change-password').onclick=()=>{const p=modal('Passwort ändern',`<form class="form-stack"><label>Aktuelles Passwort<input name="current" type="password" autocomplete="current-password" required></label><label>Neues Passwort · mindestens 12 Zeichen<input name="password" type="password" autocomplete="new-password" minlength="12" required></label><label>Neues Passwort wiederholen<input name="repeat" type="password" autocomplete="new-password" minlength="12" required></label><p id="password-error" class="error-message" role="alert"></p><button class="button">Passwort speichern</button></form>`);p.querySelector('form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(f.get('password')!==f.get('repeat')){p.querySelector('#password-error').textContent='Die neuen Passwörter stimmen nicht überein.';return;}try{await store.request('password',{method:'POST',body:{current:f.get('current'),password:f.get('password')}});p.close();toast('Passwort geändert. Andere Sitzungen werden abgemeldet.');}catch(error){p.querySelector('#password-error').textContent=error.message;}};};
  }
  if(store.user?.role==='admin')d.querySelector('#manage-users').onclick=()=>usersDialog();
}
async function usersDialog(){
  const d=modal('Deine Lerngruppe',`<p>Konten laden …</p>`);
  try{const {users}=await store.request('users');d.querySelector('.dialog-body').innerHTML=`<p>Konten werden von Admins angelegt. Startpasswörter separat mitteilen; die Plattform versendet keine E-Mails.</p><form id="user-create" class="form-stack"><label>Name<input name="name" required maxlength="150"></label><label>E-Mail<input type="email" name="email" required maxlength="254"></label><label>Startpasswort · mindestens 12 Zeichen<input type="password" name="password" autocomplete="new-password" required minlength="12"></label><label>Rolle<select name="role"><option value="user">Studierende</option><option value="editor">Editor</option><option value="admin">Admin</option></select></label><button class="button">Konto anlegen +</button><p id="user-error" role="alert" class="error-message"></p></form><div class="section"><h3>Vorhandene Konten</h3>${users.map(u=>`<div class="resource"><div><h3>${esc(u.name)}</h3><p>${esc(u.email)} · ${esc(u.role)} · ${u.active?'aktiv':'deaktiviert'}</p></div><button class="icon-button" data-edit-user="${u.id}" aria-label="${esc(u.name)} verwalten">✎</button></div>`).join('')}</div>`;
    d.querySelector('#user-create').onsubmit=async e=>{e.preventDefault();try{const values=Object.fromEntries(new FormData(e.currentTarget));await store.request('users',{method:'POST',body:{op:'create',...values}});await usersDialog();toast('Konto angelegt.');}catch(error){d.querySelector('#user-error').textContent=error.message;}};
    d.querySelectorAll('[data-edit-user]').forEach(b=>b.onclick=()=>{const u=users.find(x=>x.id===Number(b.dataset.editUser)),p=modal('Konto verwalten',`<p>${esc(u.name)} · ${esc(u.email)}</p><form class="form-stack"><label>Rolle<select name="role">${['user','editor','admin'].map(r=>`<option value="${r}" ${r===u.role?'selected':''}>${r}</option>`).join('')}</select></label><label><input type="checkbox" name="active" ${u.active?'checked':''}> Konto aktiv</label><label>Passwort zurücksetzen (optional, mindestens 12 Zeichen)<input type="password" name="password" autocomplete="new-password" minlength="12"></label><p class="error-message" id="manage-error" role="alert"></p><button class="button">Änderungen speichern</button></form>`);p.querySelector('form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await store.request('users',{method:'POST',body:{op:'update',id:u.id,role:f.get('role'),active:f.has('active'),password:f.get('password')}});await usersDialog();toast('Konto aktualisiert.');}catch(error){p.querySelector('#manage-error').textContent=error.message;}};});
  }catch(error){d.querySelector('.dialog-body').innerHTML=`<p class="error-message">${esc(error.message)}</p>`;}
}
