import {store} from './store.js';
import {esc,markdown,toast,empty,title} from './render.js';
import {lessonsOf,percent,allLessons,grade,reviewCard,safeURL} from './model.js';
const find=(cid,lid)=>{const c=store.catalog.courses.find(c=>c.id===cid);return [c,c&&lessonsOf(c).find(l=>l.id===lid)];};
const missing=root=>root.innerHTML=empty('Dieser Inhalt ist nicht verfügbar.','Öffne die Kursübersicht und wähle eine vorhandene Lektion.');
export function course(root,cid){
  const c=store.catalog.courses.find(c=>c.id===cid);if(!c)return missing(root);const ls=lessonsOf(c),p=percent(c,store.state.completed),next=ls.find(l=>!store.state.completed[l.id])||ls[0];
  root.innerHTML=`<div class="breadcrumbs"><a href="#/courses">Meine Kurse</a><span>/</span><span>${esc(c.title)}</span></div>`+title(c.title,c.description,next?`<a class="button" href="#/lesson/${esc(c.id)}/${esc(next.id)}">${p?'Weiterlernen':'Kurs beginnen'} ↗</a>`:'')+`<div class="split"><section>${c.modules.map(m=>`<div class="panel" style="margin-bottom:18px"><div class="module-title"><h2>${esc(m.title)}</h2><span class="tag">${m.lessons.length} Lektionen</span></div>${m.lessons.map((l,i)=>`<a class="lesson-row ${store.state.completed[l.id]?'done':''}" href="#/lesson/${esc(c.id)}/${esc(l.id)}"><span class="number">${store.state.completed[l.id]?'✓':String(i+1).padStart(2,'0')}</span><div><h3>${esc(l.title)}</h3><p>ca. ${Number(l.minutes)||8} Minuten ${l.quiz?'· Wissenscheck':''}</p></div><span class="arrow" aria-hidden="true">↗</span></a>`).join('')}</div>`).join('')}</section><aside><div class="panel"><span class="eyebrow">DEIN FORTSCHRITT</span><strong class="result-score">${p}%</strong><div class="progress" role="progressbar" aria-valuenow="${p}" aria-valuemin="0" aria-valuemax="100" aria-label="Kursfortschritt"><span style="width:${p}%"></span></div><p style="margin-top:15px" class="muted">${ls.filter(l=>store.state.completed[l.id]).length} von ${ls.length} Lektionen bearbeitet.</p><a class="text-button" href="#/cards/${esc(c.id)}">Karteikarten zum Kurs ↗</a></div><div class="callout">${c.status==='starter'?'Ergänzende Startinhalte mit erfundenen Lernübungen. Kein offizieller Hochschulkurs.':'Nimm dir Raum für eigene Fragen. Bearbeite den Wissenscheck und halte deinen Transfer in den privaten Notizen fest.'}</div></aside></div>`;
}
export function lesson(root,cid,lid){
  const [c,l]=find(cid,lid);if(!l)return missing(root);const ls=lessonsOf(c),idx=ls.findIndex(x=>x.id===lid),done=Boolean(store.state.completed[lid]);
  root.innerHTML=`<div class="breadcrumbs"><a href="#/courses">Meine Kurse</a><span>/</span><a href="#/course/${esc(cid)}">${esc(c.title)}</a><span>/</span><span>Lektion ${idx+1}</span></div><div class="lesson-layout"><aside class="lesson-sidebar"><span class="eyebrow">DEIN LERNPFAD</span><h3>${esc(c.title)}</h3>${c.modules.map(m=>`<h3>${esc(m.title)}</h3>${m.lessons.map(x=>`<a class="side-link ${x.id===lid?'active':''}" href="#/lesson/${esc(cid)}/${esc(x.id)}" ${x.id===lid?'aria-current="page"':''}><span>${store.state.completed[x.id]?'✓':'○'}</span>${esc(x.title)}</a>`).join('')}`).join('')}<a class="text-button" href="#/course/${esc(cid)}">← Kursübersicht</a></aside><article class="panel lesson-content"><span class="eyebrow">LEKTION ${idx+1} VON ${ls.length} · CA. ${Number(l.minutes)||8} MINUTEN</span><h1>${esc(l.title)}</h1><div class="prose">${markdown(l.content)}</div>${l.reflection?`<div class="callout"><strong>Deine Perspektive</strong><br>${esc(l.reflection)}</div>`:''}${(l.sources||[]).length?`<section class="sources"><h3>Quellen & Vertiefung</h3>${l.sources.map(s=>safeURL(s.url)?`<a href="${esc(safeURL(s.url))}" target="_blank" rel="noopener noreferrer">${esc(s.title)} ↗</a>`:'').join('')}</section>`:''}<div class="section no-print"><h3>Deine privaten Notizen</h3><p class="muted" style="font-size:11px">${store.local?'In diesem Browser gespeichert.':'Nur deinem Konto zugeordnet.'} Nutze erfundene oder anonymisierte Beispiele.</p><textarea id="lesson-note" class="note-area" maxlength="20000" aria-label="Private Notizen zur Lektion" placeholder="Was ist klar geworden? Was bleibt offen?">${esc(store.state.notes[lid]||'')}</textarea><button class="button secondary small" id="save-note">Notiz speichern</button><span id="note-status" class="muted" role="status" style="font-size:11px;margin-left:12px"></span></div><div class="lesson-actions no-print">${l.quiz?`<a class="button" href="#/quiz/${esc(cid)}/${esc(lid)}">Wissenscheck starten ↗</a>`:''}<button class="button secondary" id="complete-lesson">${done?'✓ Bearbeitet – Markierung aufheben':'Als bearbeitet markieren'}</button><button class="icon-button" id="print-lesson" aria-label="Lektion drucken">⎙</button></div><div class="lesson-actions"><a class="text-button" href="${idx?`#/lesson/${cid}/${ls[idx-1].id}`:`#/course/${cid}`}">← ${idx?'Vorherige Lektion':'Kursübersicht'}</a>${idx<ls.length-1?`<a class="text-button" href="#/lesson/${esc(cid)}/${esc(ls[idx+1].id)}">Nächste Lektion →</a>`:`<a class="text-button" href="#/course/${esc(cid)}">Zum Lernpfad →</a>`}</div></article></div>`;
  const note=root.querySelector('#lesson-note');let dirty=false;note.oninput=()=>{dirty=note.value!==(store.state.notes[lid]||'');root.querySelector('#note-status').textContent=dirty?'Noch nicht gespeichert':'';};
  const saveNote=async()=>{try{await store.mutate(s=>s.notes[lid]=note.value);dirty=false;root.querySelector('#note-status').textContent='Gespeichert';return true;}catch(e){toast(e.message);return false;}};
  root.querySelector('#save-note').onclick=saveNote;
  root.querySelector('#complete-lesson').onclick=async()=>{if(dirty&&!await saveNote())return;try{await store.mutate(s=>{s.completed[lid]=!done;s.lastLesson=lid;});lesson(root,cid,lid);toast(done?'Markierung aufgehoben.':'Lektion als bearbeitet markiert.');}catch(e){toast(e.message);}};
  root.querySelector('#print-lesson').onclick=()=>window.print();
  // Ein sichtbarer Speichern-Knopf bleibt die klare Zusage. Bei Navigation im
  // Lernbereich werden offene Notizen zusätzlich gespeichert.
  root.querySelectorAll('a[href^="#/"]').forEach(a=>a.addEventListener('click',async e=>{if(dirty){e.preventDefault();if(await saveNote())location.hash=a.getAttribute('href');}}));
  store.mutate(s=>s.lastLesson=lid).catch(e=>toast(e.message));
}
export function quiz(root,cid,lid){
  const [c,l]=find(cid,lid);if(!l?.quiz)return missing(root);const questions=l.quiz.questions;
  root.innerHTML=`<div class="breadcrumbs"><a href="#/lesson/${esc(cid)}/${esc(lid)}">← Zur Lektion</a></div>`+title('Was bleibt hängen?',`Wissenscheck · ${l.title}`)+`<form id="quiz-form" class="panel" style="max-width:850px"><span class="eyebrow">${questions.length} FRAGE${questions.length===1?'':'N'} · ${l.quiz.passingScore} RICHTIGE ZUM BESTEHEN</span>${questions.map((q,i)=>`<fieldset class="quiz-question" style="border:0;padding:0"><legend style="width:100%"><h3>${i+1}. ${esc(q.title)}</h3></legend><p class="muted" style="font-size:11px">${q.type==='multiple'?'Mehrere Antworten möglich. Wähle alle passenden Antworten.':'Wähle genau eine Antwort.'}</p>${q.answers.map(a=>`<label class="answer"><input type="${q.type==='multiple'?'checkbox':'radio'}" name="${esc(q.id)}" value="${esc(a.id)}"><span>${esc(a.text)}</span></label>`).join('')}<div id="feedback-${esc(q.id)}"></div></fieldset>`).join('')}<div class="form-actions"><button class="button" id="check-quiz">Antworten prüfen ↗</button><a class="button secondary" href="#/lesson/${esc(cid)}/${esc(lid)}">Zur Lektion</a></div><p id="quiz-status" role="status" style="margin-top:16px"></p></form>`;
  root.querySelector('#quiz-form').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form);if(questions.some(q=>!f.getAll(q.id).length)){toast('Beantworte bitte jede Frage.');return;}
    const evaluated=questions.map(q=>({question:q,correct:grade(q,f.getAll(q.id))})),score=evaluated.filter(x=>x.correct).length,passed=score>=l.quiz.passingScore;
    const button=form.querySelector('#check-quiz');button.disabled=true;
    try{await store.mutate(s=>{s.quizResults[lid]={score,total:questions.length,passed,at:new Date().toISOString()};if(passed)s.completed[lid]=true;});
      evaluated.forEach(({question:q,correct})=>{form.querySelector(`#feedback-${q.id}`).innerHTML=`<div class="feedback ${correct?'correct':''}"><strong>${correct?'Richtig.':'Noch nicht ganz.'}</strong> ${esc(q.explanation)}${correct?'':`<br>Passende Antwort${q.answers.filter(a=>a.isCorrect).length>1?'en':''}: ${q.answers.filter(a=>a.isCorrect).map(a=>esc(a.text)).join('; ')}`}</div>`;});
      form.querySelectorAll('input').forEach(i=>i.disabled=true);form.querySelector('#quiz-status').innerHTML=`<strong>${score} von ${questions.length} richtig.</strong> ${passed?'Bestanden. Die Lektion ist als bearbeitet markiert.':'Du kannst die Lektion erneut lesen und den Check wiederholen.'}`;
      button.type='button';button.textContent='Erneut versuchen';button.disabled=false;button.onclick=()=>quiz(root,cid,lid);
    }catch(error){toast(error.message);button.disabled=false;}
  };
}
export function cards(root,cid=null){
  root.innerHTML=title('Wissen wiedersehen.','Erst selbst antworten, dann aufdecken. So erkennst du, was du schon abrufen kannst.')+`<div class="toolbar"><label>Kurs<select id="card-course"><option value="all">Alle Kurse</option>${store.catalog.courses.map(c=>`<option value="${esc(c.id)}" ${c.id===cid?'selected':''}>${esc(c.title)}</option>`).join('')}</select></label><div class="filters"><button class="filter active" data-mode="all">Alle Karten</button><button class="filter" data-mode="due">Jetzt fällig</button></div></div><div id="card-stage" class="card-stage"></div>`;
  const deck=allLessons(store.catalog).flatMap(l=>(l.flashcards||[]).map((f,i)=>({...f,id:`${l.id}_${i}`,courseId:l.courseId,courseTitle:l.courseTitle})));
  let mode='all',currentDeck=[],index=0,flipped=false;
  const reset=()=>{const selected=root.querySelector('#card-course').value;currentDeck=deck.filter(c=>(selected==='all'||c.courseId===selected)&&(mode==='all'||!store.state.reviews[c.id]||store.state.reviews[c.id].due<=Date.now()));index=0;flipped=false;draw();};
  const draw=()=>{const stage=root.querySelector('#card-stage');if(!currentDeck.length){stage.innerHTML=empty('Gerade nichts zu wiederholen.',mode==='due'?'Alle Karten dieses Kurses sind noch nicht fällig. Wähle „Alle Karten“, wenn du weiterlernen möchtest.':'Für diesen Kurs sind noch keine Karten hinterlegt.');return;}if(index>=currentDeck.length){stage.innerHTML=`<div class="panel" style="text-align:center"><span class="eyebrow">GUTER LERNSCHRITT</span><h2>Eine Runde weiter.</h2><p style="margin:20px 0">Du hast ${currentDeck.length} Karten eingeschätzt. Dein nächster Wiederholungstermin ist gespeichert.</p><button class="button" id="restart-cards">Neue Runde ↗</button></div>`;stage.querySelector('#restart-cards').onclick=reset;return;}
    const c=currentDeck[index];stage.innerHTML=`<p class="card-progress">Karte ${index+1} von ${currentDeck.length} · ${esc(c.courseTitle)}</p><button class="flashcard" id="flip-card" aria-label="${flipped?'Vorderseite anzeigen':'Antwort aufdecken'}"><span class="card-label">${flipped?'DEINE ANTWORT ZUM VERGLEICHEN':'DEINE FRAGE'}</span>${flipped?`<p>${esc(c.a)}</p>`:`<h2>${esc(c.q)}</h2>`}<small>${flipped?'Zum Zurückdrehen antippen':'Denk kurz nach. Tippe zum Aufdecken.'}</small></button>${flipped?`<div class="ratings"><button class="button secondary" data-rating="again">Nochmal <small>10 Min.</small></button><button class="button secondary" data-rating="hard">Schwer <small>1 Tag</small></button><button class="button" data-rating="good">Gewusst <small>${reviewCard(store.state.reviews[c.id],'good').interval} Tage</small></button></div>`:`<div class="ratings"><button class="button" id="reveal-card">Antwort aufdecken ↗</button></div>`}<p class="card-progress">Die Einschätzung ist für dich persönlich. Es gibt keine Bewertung durch andere.</p>`;
    const flip=()=>{flipped=!flipped;draw();};stage.querySelector('#flip-card').onclick=flip;if(!flipped)stage.querySelector('#reveal-card').onclick=flip;
    stage.querySelectorAll('[data-rating]').forEach(b=>b.onclick=async()=>{stage.querySelectorAll('[data-rating]').forEach(x=>x.disabled=true);try{await store.mutate(s=>s.reviews[c.id]=reviewCard(s.reviews[c.id],b.dataset.rating));index++;flipped=false;draw();}catch(e){toast(e.message);draw();}});
  };
  root.querySelector('#card-course').onchange=reset;root.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;root.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('active',x===b));reset();});reset();
}
